# Generated by Django 2.0.3 on 2020-04-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='subs',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sub',
            name='menu_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='orders.MenuItem'),
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='menu_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_platter', to='orders.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_items', to='orders.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.MenuItem'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='menu_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='orders.MenuItem'),
        ),
    ]
