# Generated by Django 2.0.3 on 2020-04-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200411_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='img',
            field=models.CharField(default='orders/images/dish1.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='enter description', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(default='enter descriotion', max_length=100),
        ),
    ]
