# Generated by Django 2.0.3 on 2020-04-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200412_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='orders.Menu'),
        ),
    ]
