# Generated by Django 3.0.5 on 2020-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200412_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatter',
            name='large_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='medium_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='small_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='large_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='medium_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='small_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='medium_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
