# Generated by Django 3.0.5 on 2020-04-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200412_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='orders.Menu'),
        ),
    ]
