# Generated by Django 3.0.5 on 2020-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200412_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('pizza', 'pizza'), ('dinner platter', 'dinner_platter'), ('pasta', 'pasta'), ('salad', 'salad'), ('sub', 'sub')], max_length=20),
        ),
    ]
