# Generated by Django 2.2.12 on 2020-04-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200415_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='menu_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='orders.MenuItem'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='orders.OrderItem'),
        ),
    ]
