# Generated by Django 2.2.12 on 2020-04-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200415_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='orders.OrderItem'),
        ),
    ]
